version: '3.8'

services:
  test-runner:
    build:
      context: .
      target: test_runner
    depends_on:
      - db
    env_file:
      - test.env
    environment:
      - APP_ENV=test
  db:
    image: postgres:15-alpine
    volumes:
      - ./infra/common/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    env_file:
      - infra/test_runner/docker/db.env
